image: lorisleiva/laravel-docker:latest
composer:
  stage: build
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
codestyle:
  stage: test
  cache: {}
  dependencies: []
  script:
    - phpcs --standard=PSR2 --extensions=php src
phpunit:
  stage: test
  dependencies:
    - composer
  script:
    - phpunit --coverage-text --colors=never
